### PR TITLE
Add Steam Workshop Preview Image

### PR DESCRIPTION
**Pull request by WUOTE**
I've manually tested the mod and confirm that its working with no apparent added delay to the game start.

What needs to be done is: 

1. Perform a dry run with writing every accel seed output to file (you can use the method I use to write to file in [SEEDiz](https://github.com/WUOTE/seediz) to compare with the output we got running pudy's CUDA-powered seed search tool.
2. Submit mod to workshop (I've went ahead and created artwork for it).

Following previous conversation with Letaali, I suggest opening a discussion on [speedrun.com](https://www.speedrun.com/noita/forums) with the proposal of adding the mod to the list of approved seeds. Please mention that there are `103,794,048` accel-only-start seeds to inform others of the amount of seeds available, so they can decide if "_random seed starts to sound less and less random_" or not.
The biggest gap between seeds with accel start is `364`
biggest_gap_between_accel_seeds

### CODE REVIEW

**Comment by tehkab** [comment]
I would prefer not using the speedrun.com branding in the workshop preview image, both to avoid the appearance of endorsement and also because it's probably not a permitted use of their copyright/etc.

Also as that discussion has yet to be had, it implies use of the mod is acceptable when that hasn't yet been decided by the greater speedrunning community.

I'll take a look at generating the seed list via the mod's test. Might take a while 😅

**Comment by WUOTE** [comment]
> I would prefer not using the speedrun.com branding in the workshop preview image, both to avoid the appearance of endorsement and also because it's probably not a permitted use of their copyright/etc.
> 
> Also as that discussion has yet to be had, it implies use of the mod is acceptable when that hasn't yet been decided by the greater speedrunning community.
> 
> I'll take a look at generating the seed list via the mod's test. Might take a while 😅

Fair
in the meantime, maybe use this?
workshop_preview_image2

**Comment by tehkab** [comment]
Maybe "Acceleratium Starts ONLY", flip the wording around a bit? Otherwise looks good

Either way if you could commit that change / add it to the PR, that would be great

**Comment by WUOTE** [comment]
> Maybe "Acceleratium Starts ONLY", flip the wording around a bit? Otherwise looks good
> 
> Either way if you could commit that change / add it to the PR, that would be great

Should be correct now 21e0feda3c9ec1870c3bf89f1fab646daabfd038.

**Pull request merged**
